### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Profex1999** [PichotM/pVoice#3]
![missing](https://user-images.githubusercontent.com/51895814/79353938-08c33e80-7f3c-11ea-9040-67628f98904e.PNG)
 Where can I find this resource? I was looking for it in your repositories but didn't find anything

**Comment by Sytrookie** [comment]
True can't find your libs anywhere, will they be available?

**Comment by Kathou99** [comment]
Did you have find the depency below it's look like is in the core 'pitchot_core'?

	'@pichot_core/sh_core.lua',
	'@pichot_core/cl_core.lua',
	'@pichot_core/cl_players.lua',
	"@pichot_core/sv_core.lua",
